# Generated by Django 4.2 on 2025-05-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueEditable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contenido_html', models.TextField()),
                ('estilos_css', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
