# Generated by Django 4.2 on 2025-06-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeandblogv1', '0002_bloqueeditable_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueeditable',
            name='aparece_en_inicio',
            field=models.BooleanField(default=True),
        ),
    ]
