# Generated by Django 4.2 on 2025-06-12 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeandblogv1', '0003_bloqueeditable_aparece_en_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueeditable',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'svg'])]),
        ),
    ]
